export const ActionType = {
    SET_PRODUCT: "SET_PRODUCT",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_PRODUCT: "REMOVE_PRODUCT",
    ADD_TO_CART: "ADD_TO_CART",
    CART_SIZE:"CART_SIZE",
}